package com.supercompany.miragerh.ihm.creer;

import com.supercompany.miragerh.ihm.popup.ConfirmationPopUp;
import com.supercompany.miragerh.ihm.popup.ErrorPopUp;
import fr.jaschavolp.m1.jee.mirageshared.fichedeposte.CreateFichePosteVM;
import fr.jaschavolp.m1.jee.mirageshared.presentationentreprise.PresentationEntrepriseVM;
import fr.jaschavolp.m1.jee.mirageshared.shared.exceptions.IdentifiantInvalideException;
import fr.jaschavolp.m1.jee.mirageshared.shared.services.ServicesRHRemote;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 * Définit une JPanel personnalisé pour la création d'une nouvelle fiche de poste
 * @author FlorianDELSOL
 */
public class CreerFicheDePoste extends javax.swing.JPanel {
    
    private int identifiantDemandeDeCompetence;
    
    private ServicesRHRemote service;
    
    private List<PresentationEntrepriseVM> presentation;

    /**
     * Créer une nouvelle isntance
     * @param identifiantDemandeDeCompetence L'identifiant de la demande de compétence
     * @param service Le service permettant de communiquer avec le serveur
     * @param presentation La liste des présentationd d'entreprise existante
     */
    public CreerFicheDePoste(int identifiantDemandeDeCompetence, ServicesRHRemote service, List<PresentationEntrepriseVM> presentation) {
        initComponents();
        this.identifiantDemandeDeCompetence = identifiantDemandeDeCompetence;
        this.service = service;
        
        presentation.forEach((vm) -> {
            jComboBoxPresentationExistante.addItem(vm.getIdentifiant() + "- " + vm.getNom());
        });
        
        if(presentation.isEmpty()){
            jRadioButtonPresentationEntrepriseExistante.setEnabled(false);
            jRadioButtonPresentationEntrepriseExistante.setSelected(false);
            jRadioButtonNouvellePresentation.setSelected(true);
            jComboBoxPresentationExistante.setEnabled(false);
        }else{
            jRadioButtonNouvellePresentation.setSelected(false);
            jTextAreaNouvellePresentationEntreprise.setEnabled(false);
            jTextFieldNomNouvellePresentationEntreprise.setEnabled(false);
            jRadioButtonPresentationEntrepriseExistante.setSelected(true);
            jComboBoxPresentationExistante.setEnabled(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelContainer = new javax.swing.JPanel();
        jLabelNomFicheTitle = new javax.swing.JLabel();
        jPanelPresentationPoste = new javax.swing.JPanel();
        jLabelPresentationPosteTitre = new javax.swing.JLabel();
        jScrollPanePresentationPoste = new javax.swing.JScrollPane();
        jTextAreaPresentationPoste = new javax.swing.JTextArea();
        jPanelPresentationEntreprise = new javax.swing.JPanel();
        jLabelPresentationEntrepriseTitre = new javax.swing.JLabel();
        jPanelPresentationEntrepriseExistante = new javax.swing.JPanel();
        jRadioButtonPresentationEntrepriseExistante = new javax.swing.JRadioButton();
        jComboBoxPresentationExistante = new javax.swing.JComboBox<>();
        jPanelNouvellePresentationEntreprise = new javax.swing.JPanel();
        jRadioButtonNouvellePresentation = new javax.swing.JRadioButton();
        jScrollPaneNouvellePresentationEntreprise = new javax.swing.JScrollPane();
        jTextAreaNouvellePresentationEntreprise = new javax.swing.JTextArea();
        jTextFieldNomNouvellePresentationEntreprise = new javax.swing.JTextField();
        jButtonValider = new javax.swing.JButton();
        jTextFieldNomFicheData = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanelContainer.setBackground(new java.awt.Color(250, 250, 255));

        jLabelNomFicheTitle.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabelNomFicheTitle.setText("Nom de la fiche : ");

        jPanelPresentationPoste.setBackground(new java.awt.Color(250, 250, 255));

        jLabelPresentationPosteTitre.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabelPresentationPosteTitre.setText("Présentation du poste :");

        jTextAreaPresentationPoste.setColumns(20);
        jTextAreaPresentationPoste.setRows(5);
        jScrollPanePresentationPoste.setViewportView(jTextAreaPresentationPoste);

        javax.swing.GroupLayout jPanelPresentationPosteLayout = new javax.swing.GroupLayout(jPanelPresentationPoste);
        jPanelPresentationPoste.setLayout(jPanelPresentationPosteLayout);
        jPanelPresentationPosteLayout.setHorizontalGroup(
            jPanelPresentationPosteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPresentationPosteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelPresentationPosteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelPresentationPosteLayout.createSequentialGroup()
                        .addComponent(jScrollPanePresentationPoste)
                        .addContainerGap())
                    .addGroup(jPanelPresentationPosteLayout.createSequentialGroup()
                        .addComponent(jLabelPresentationPosteTitre, javax.swing.GroupLayout.DEFAULT_SIZE, 420, Short.MAX_VALUE)
                        .addGap(294, 294, 294))))
        );
        jPanelPresentationPosteLayout.setVerticalGroup(
            jPanelPresentationPosteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPresentationPosteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelPresentationPosteTitre, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPanePresentationPoste, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanelPresentationEntreprise.setBackground(new java.awt.Color(250, 250, 255));

        jLabelPresentationEntrepriseTitre.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabelPresentationEntrepriseTitre.setText("Présentation de l'entreprise :");

        jRadioButtonPresentationEntrepriseExistante.setSelected(true);
        jRadioButtonPresentationEntrepriseExistante.setText("Présentation existante");
        jRadioButtonPresentationEntrepriseExistante.setToolTipText("");
        jRadioButtonPresentationEntrepriseExistante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonPresentationEntrepriseExistanteActionPerformed(evt);
            }
        });

        jComboBoxPresentationExistante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxPresentationExistanteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelPresentationEntrepriseExistanteLayout = new javax.swing.GroupLayout(jPanelPresentationEntrepriseExistante);
        jPanelPresentationEntrepriseExistante.setLayout(jPanelPresentationEntrepriseExistanteLayout);
        jPanelPresentationEntrepriseExistanteLayout.setHorizontalGroup(
            jPanelPresentationEntrepriseExistanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jRadioButtonPresentationEntrepriseExistante, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
            .addGroup(jPanelPresentationEntrepriseExistanteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jComboBoxPresentationExistante, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelPresentationEntrepriseExistanteLayout.setVerticalGroup(
            jPanelPresentationEntrepriseExistanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPresentationEntrepriseExistanteLayout.createSequentialGroup()
                .addComponent(jRadioButtonPresentationEntrepriseExistante)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBoxPresentationExistante, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(129, Short.MAX_VALUE))
        );

        jRadioButtonNouvellePresentation.setText("Nouvelle présentation");
        jRadioButtonNouvellePresentation.setToolTipText("");
        jRadioButtonNouvellePresentation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonNouvellePresentationActionPerformed(evt);
            }
        });

        jTextAreaNouvellePresentationEntreprise.setColumns(20);
        jTextAreaNouvellePresentationEntreprise.setRows(5);
        jTextAreaNouvellePresentationEntreprise.setText("Présentation");
        jScrollPaneNouvellePresentationEntreprise.setViewportView(jTextAreaNouvellePresentationEntreprise);

        jTextFieldNomNouvellePresentationEntreprise.setText("Nom de la nouvelle présentation");

        javax.swing.GroupLayout jPanelNouvellePresentationEntrepriseLayout = new javax.swing.GroupLayout(jPanelNouvellePresentationEntreprise);
        jPanelNouvellePresentationEntreprise.setLayout(jPanelNouvellePresentationEntrepriseLayout);
        jPanelNouvellePresentationEntrepriseLayout.setHorizontalGroup(
            jPanelNouvellePresentationEntrepriseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jRadioButtonNouvellePresentation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanelNouvellePresentationEntrepriseLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelNouvellePresentationEntrepriseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPaneNouvellePresentationEntreprise)
                    .addComponent(jTextFieldNomNouvellePresentationEntreprise))
                .addContainerGap())
        );
        jPanelNouvellePresentationEntrepriseLayout.setVerticalGroup(
            jPanelNouvellePresentationEntrepriseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelNouvellePresentationEntrepriseLayout.createSequentialGroup()
                .addComponent(jRadioButtonNouvellePresentation)
                .addGap(7, 7, 7)
                .addComponent(jTextFieldNomNouvellePresentationEntreprise, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPaneNouvellePresentationEntreprise)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanelPresentationEntrepriseLayout = new javax.swing.GroupLayout(jPanelPresentationEntreprise);
        jPanelPresentationEntreprise.setLayout(jPanelPresentationEntrepriseLayout);
        jPanelPresentationEntrepriseLayout.setHorizontalGroup(
            jPanelPresentationEntrepriseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPresentationEntrepriseLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelPresentationEntrepriseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelPresentationEntrepriseLayout.createSequentialGroup()
                        .addComponent(jLabelPresentationEntrepriseTitre, javax.swing.GroupLayout.DEFAULT_SIZE, 420, Short.MAX_VALUE)
                        .addGap(294, 294, 294))
                    .addGroup(jPanelPresentationEntrepriseLayout.createSequentialGroup()
                        .addComponent(jPanelPresentationEntrepriseExistante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanelNouvellePresentationEntreprise, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        jPanelPresentationEntrepriseLayout.setVerticalGroup(
            jPanelPresentationEntrepriseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPresentationEntrepriseLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelPresentationEntrepriseTitre, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelPresentationEntrepriseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelPresentationEntrepriseExistante, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelNouvellePresentationEntreprise, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jButtonValider.setText("Valider");
        jButtonValider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonValiderActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelContainerLayout = new javax.swing.GroupLayout(jPanelContainer);
        jPanelContainer.setLayout(jPanelContainerLayout);
        jPanelContainerLayout.setHorizontalGroup(
            jPanelContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelContainerLayout.createSequentialGroup()
                        .addComponent(jLabelNomFicheTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldNomFicheData)
                        .addGap(10, 10, 10))
                    .addComponent(jPanelPresentationPoste, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelPresentationEntreprise, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanelContainerLayout.createSequentialGroup()
                .addGap(260, 260, 260)
                .addComponent(jButtonValider, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addGap(297, 297, 297))
        );
        jPanelContainerLayout.setVerticalGroup(
            jPanelContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNomFicheTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextFieldNomFicheData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanelPresentationPoste, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jPanelPresentationEntreprise, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonValider)
                .addGap(26, 26, 26))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelContainer, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelContainer, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonValiderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonValiderActionPerformed
        
        CreateFichePosteVM vm = null;
        if(jTextFieldNomFicheData.getText().trim().length()==0 || jTextFieldNomFicheData.getText().trim().length() ==0){
            ErrorPopUp popUp = new ErrorPopUp("Veuillez entrer un nom de fiche et une description du poste");
            return;
        }
        if(jRadioButtonPresentationEntrepriseExistante.isSelected()){
            vm = new CreateFichePosteVM(identifiantDemandeDeCompetence, jTextFieldNomFicheData.getText(), jTextAreaPresentationPoste.getText(), false, Integer.parseInt(((String)jComboBoxPresentationExistante.getSelectedItem()).split("-")[0]) , null, null);
        }else if(jRadioButtonNouvellePresentation.isSelected()){
            if(jTextAreaNouvellePresentationEntreprise.getText().trim().length()==0 || jTextFieldNomNouvellePresentationEntreprise.getText().trim().length()==0){
                ErrorPopUp popUp = new ErrorPopUp("Veuillez entrer un nouveau nom et une nouvelle présentation d'entreprise");
                return;
            }
            vm = new CreateFichePosteVM(identifiantDemandeDeCompetence, jTextFieldNomFicheData.getText(), jTextAreaPresentationPoste.getText(), true, -1, jTextFieldNomNouvellePresentationEntreprise.getText(), jTextAreaNouvellePresentationEntreprise.getText());
        }else{
            return;
        }
        try {
            service.creerUneFicheDePoste(vm);
            ConfirmationPopUp confPopUp = new ConfirmationPopUp("La fiche de poste a bien été envoyée");
        } catch (IdentifiantInvalideException ex) {
            Logger.getLogger(CreerFicheDePoste.class.getName()).log(Level.SEVERE, null, ex);
            ErrorPopUp popUp = new ErrorPopUp("Erreur : la fiche n'a pas été créé " + ex.getMessage());
        }
    }//GEN-LAST:event_jButtonValiderActionPerformed

    private void jRadioButtonPresentationEntrepriseExistanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonPresentationEntrepriseExistanteActionPerformed
        jRadioButtonNouvellePresentation.setSelected(false);
        jTextAreaNouvellePresentationEntreprise.setEnabled(false);
        jTextFieldNomNouvellePresentationEntreprise.setEnabled(false);
        jRadioButtonPresentationEntrepriseExistante.setSelected(true);
        jComboBoxPresentationExistante.setEnabled(true);
    }//GEN-LAST:event_jRadioButtonPresentationEntrepriseExistanteActionPerformed

    private void jRadioButtonNouvellePresentationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonNouvellePresentationActionPerformed
        jRadioButtonNouvellePresentation.setSelected(true);
        jTextAreaNouvellePresentationEntreprise.setEnabled(true);
        jTextFieldNomNouvellePresentationEntreprise.setEnabled(true);
        jRadioButtonPresentationEntrepriseExistante.setSelected(false);
        jComboBoxPresentationExistante.setEnabled(false);
    }//GEN-LAST:event_jRadioButtonNouvellePresentationActionPerformed

    private void jComboBoxPresentationExistanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxPresentationExistanteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxPresentationExistanteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonValider;
    private javax.swing.JComboBox<String> jComboBoxPresentationExistante;
    private javax.swing.JLabel jLabelNomFicheTitle;
    private javax.swing.JLabel jLabelPresentationEntrepriseTitre;
    private javax.swing.JLabel jLabelPresentationPosteTitre;
    private javax.swing.JPanel jPanelContainer;
    private javax.swing.JPanel jPanelNouvellePresentationEntreprise;
    private javax.swing.JPanel jPanelPresentationEntreprise;
    private javax.swing.JPanel jPanelPresentationEntrepriseExistante;
    private javax.swing.JPanel jPanelPresentationPoste;
    private javax.swing.JRadioButton jRadioButtonNouvellePresentation;
    private javax.swing.JRadioButton jRadioButtonPresentationEntrepriseExistante;
    private javax.swing.JScrollPane jScrollPaneNouvellePresentationEntreprise;
    private javax.swing.JScrollPane jScrollPanePresentationPoste;
    private javax.swing.JTextArea jTextAreaNouvellePresentationEntreprise;
    private javax.swing.JTextArea jTextAreaPresentationPoste;
    private javax.swing.JTextField jTextFieldNomFicheData;
    private javax.swing.JTextField jTextFieldNomNouvellePresentationEntreprise;
    // End of variables declaration//GEN-END:variables
}
