/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.supercompany.miragerh.ihm;


import com.supercompany.miragerh.ihm.creer.CreerFicheDePoste;
import com.supercompany.miragerh.ihm.creer.FinContrat;
import com.supercompany.miragerh.ihm.creer.RecruterCandidat;
import com.supercompany.miragerh.ihm.details.DetailsCandidature;
import com.supercompany.miragerh.ihm.details.DetailsCollaborateur;
import com.supercompany.miragerh.ihm.details.DetailsDemandeDeCompetences;
import com.supercompany.miragerh.ihm.details.DetailsFicheDePoste;
import com.supercompany.miragerh.ihm.popup.ErrorPopUp;
import com.supercompany.miragerh.ihm.table.CellRenderer.BlueTableColoredCellRenderer;
import com.supercompany.miragerh.ihm.table.TableModel.CandidatureTableModel;
import com.supercompany.miragerh.ihm.table.TableModel.CollaborateurTableModel;
import com.supercompany.miragerh.ihm.table.TableModel.DmdCompetenceTableModel;
import com.supercompany.miragerh.ihm.table.TableModel.FicheDePosteTableModel;
import com.supercompany.miragerh.services.RMIRHClientService;
import fr.jaschavolp.m1.jee.mirageshared.candidature.CandidatureVM;
import fr.jaschavolp.m1.jee.mirageshared.candidature.DetailsCandidatureVM;
import fr.jaschavolp.m1.jee.mirageshared.dmdcompetences.DmdCompetencesVM;
import fr.jaschavolp.m1.jee.mirageshared.fichedeposte.DetailsFichePosteVM;
import fr.jaschavolp.m1.jee.mirageshared.fichedeposte.FichePosteVM;
import fr.jaschavolp.m1.jee.mirageshared.personne.collaborateur.CollaborateurVM;
import fr.jaschavolp.m1.jee.mirageshared.presentationentreprise.PresentationEntrepriseVM;
import fr.jaschavolp.m1.jee.mirageshared.shared.services.ServicesRHRemote;
import java.awt.Color;
import java.awt.GridLayout;
import java.awt.ScrollPane;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.naming.NamingException;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.event.ListSelectionEvent;

/**
 * Décrit une JFrame de l'application MIA pour les Managers d'équipe
 * @author FlorianDELSOL
 */
public class Canvas extends javax.swing.JFrame {
    
    /**
     * Singleton
     */
    private static Canvas canvas;
    
    /**
     * Service permettant la communication avec le serveur
    */
    private final ServicesRHRemote service;

    /**
     * Creer une nouvelle instance de classe Canvas
     * @throws javax.naming.NamingException
     */
    private Canvas() throws NamingException {
        initComponents();
        service = new RMIRHClientService().getDabRemoteSvc();
        jLabelTitle.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        jSplitPane = new javax.swing.JSplitPane();
        leftSplitBackground = new javax.swing.JPanel();
        boutons = new javax.swing.JPanel();
        jButtonDemandeDeCompetence = new javax.swing.JButton();
        jButtonFicheDePoste = new javax.swing.JButton();
        jButtonCollaborateur = new javax.swing.JButton();
        jPanelTitreApplication = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        rightSplitBackground = new javax.swing.JPanel();
        jPanelHeader = new javax.swing.JPanel();
        jLabelTitle = new javax.swing.JLabel();
        jScrollPaneBody = new javax.swing.JScrollPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(960, 540));
        setSize(new java.awt.Dimension(960, 540));

        background.setBackground(new java.awt.Color(255, 255, 255));

        leftSplitBackground.setBackground(new java.awt.Color(50, 50, 98));

        boutons.setBackground(new java.awt.Color(50, 50, 98));
        boutons.setEnabled(false);
        boutons.setLayout(new java.awt.GridLayout(10, 0));

        jButtonDemandeDeCompetence.setBackground(new java.awt.Color(50, 50, 98));
        jButtonDemandeDeCompetence.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonDemandeDeCompetence.setForeground(new java.awt.Color(255, 255, 255));
        jButtonDemandeDeCompetence.setText("Demandes de compétences");
        jButtonDemandeDeCompetence.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDemandeDeCompetenceActionPerformed(evt);
            }
        });
        boutons.add(jButtonDemandeDeCompetence);

        jButtonFicheDePoste.setBackground(new java.awt.Color(50, 50, 98));
        jButtonFicheDePoste.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonFicheDePoste.setForeground(new java.awt.Color(255, 255, 255));
        jButtonFicheDePoste.setText("Fiches de postes");
        jButtonFicheDePoste.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFicheDePosteActionPerformed(evt);
            }
        });
        boutons.add(jButtonFicheDePoste);

        jButtonCollaborateur.setBackground(new java.awt.Color(50, 50, 98));
        jButtonCollaborateur.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonCollaborateur.setForeground(new java.awt.Color(255, 255, 255));
        jButtonCollaborateur.setText("Collaborateur");
        jButtonCollaborateur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCollaborateurActionPerformed(evt);
            }
        });
        boutons.add(jButtonCollaborateur);

        jPanelTitreApplication.setBackground(new java.awt.Color(50, 50, 98));

        jLabel3.setFont(new java.awt.Font("Vladimir Script", 0, 33)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("MIA for RH");

        javax.swing.GroupLayout jPanelTitreApplicationLayout = new javax.swing.GroupLayout(jPanelTitreApplication);
        jPanelTitreApplication.setLayout(jPanelTitreApplicationLayout);
        jPanelTitreApplicationLayout.setHorizontalGroup(
            jPanelTitreApplicationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTitreApplicationLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelTitreApplicationLayout.setVerticalGroup(
            jPanelTitreApplicationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTitreApplicationLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout leftSplitBackgroundLayout = new javax.swing.GroupLayout(leftSplitBackground);
        leftSplitBackground.setLayout(leftSplitBackgroundLayout);
        leftSplitBackgroundLayout.setHorizontalGroup(
            leftSplitBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(boutons, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelTitreApplication, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        leftSplitBackgroundLayout.setVerticalGroup(
            leftSplitBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftSplitBackgroundLayout.createSequentialGroup()
                .addComponent(jPanelTitreApplication, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(boutons, javax.swing.GroupLayout.DEFAULT_SIZE, 418, Short.MAX_VALUE))
        );

        jSplitPane.setLeftComponent(leftSplitBackground);

        rightSplitBackground.setBackground(new java.awt.Color(50, 50, 98));

        jPanelHeader.setBackground(new java.awt.Color(50, 50, 98));

        jLabelTitle.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabelTitle.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitle.setText("Titre de la page");

        javax.swing.GroupLayout jPanelHeaderLayout = new javax.swing.GroupLayout(jPanelHeader);
        jPanelHeader.setLayout(jPanelHeaderLayout);
        jPanelHeaderLayout.setHorizontalGroup(
            jPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 686, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelHeaderLayout.setVerticalGroup(
            jPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
                .addContainerGap())
        );

        jScrollPaneBody.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout rightSplitBackgroundLayout = new javax.swing.GroupLayout(rightSplitBackground);
        rightSplitBackground.setLayout(rightSplitBackgroundLayout);
        rightSplitBackgroundLayout.setHorizontalGroup(
            rightSplitBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPaneBody)
        );
        rightSplitBackgroundLayout.setVerticalGroup(
            rightSplitBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rightSplitBackgroundLayout.createSequentialGroup()
                .addComponent(jPanelHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPaneBody, javax.swing.GroupLayout.DEFAULT_SIZE, 428, Short.MAX_VALUE))
        );

        jSplitPane.setRightComponent(rightSplitBackground);

        javax.swing.GroupLayout backgroundLayout = new javax.swing.GroupLayout(background);
        background.setLayout(backgroundLayout);
        backgroundLayout.setHorizontalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane)
        );
        backgroundLayout.setVerticalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Traitement lancé suite au clic sur le bouton Fiche de Poste dans le menu
     * @param evt 
     */
    private void jButtonFicheDePosteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFicheDePosteActionPerformed
        goToListeFicheDePoste();
    }//GEN-LAST:event_jButtonFicheDePosteActionPerformed

    /**
     * Traitement lancé suite au clic sur le bouton DemandeDeCompetence dans le menu
     * @param evt 
     */
    private void jButtonDemandeDeCompetenceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDemandeDeCompetenceActionPerformed
        goToListeDemandesDeCompetence();
    }//GEN-LAST:event_jButtonDemandeDeCompetenceActionPerformed

    /**
     * Traitement lancé suite au clic sur le bouton Collaborateur dans le menu
     * @param evt 
     */
    private void jButtonCollaborateurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCollaborateurActionPerformed
        // TODO add your handling code here:
        goToListeCollaborateur();
    }//GEN-LAST:event_jButtonCollaborateurActionPerformed

    private void changerPanel(JPanel p){
        jScrollPaneBody.setViewportView(p);
        this.repaint();
        this.revalidate();
    }
    
    public void goToNothing(){
        JPanel jpanel = new JPanel();
        jpanel.setBackground(Color.white);
        changerPanel(jpanel);
    }
    
    public void goToListeCollaborateur(){
        List<CollaborateurVM> viewModel = service.consulterLesCollaborateurs();
        Contenu contenu = new Contenu();
        JPanel panelListe = new JPanel(new GridLayout());
        JTable tableauCollaborateur = new JTable(new CollaborateurTableModel(viewModel));
        panelListe.add(new JScrollPane(tableauCollaborateur), new GridLayout());
        contenu.setPanelIndex(panelListe);
        tableauCollaborateur.setDefaultRenderer(Object.class, new BlueTableColoredCellRenderer());
        tableauCollaborateur.getSelectionModel().addListSelectionListener((ListSelectionEvent e) ->{
            contenu.setPanelDetail(new DetailsCollaborateur(viewModel.stream().filter((data) -> data.getIdentifiant().toString().equals(tableauCollaborateur.getValueAt(tableauCollaborateur.getSelectedRow(), 0).toString())).findFirst().orElse(null)));
        });
        jLabelTitle.setText("Liste des collaborateurs");
        changerPanel(contenu);
    }
    
    public void goToMettreFinContrat(int identifiantCollaborateur){
        FinContrat jpanel = new FinContrat(identifiantCollaborateur, service);
        changerPanel(jpanel);
    }
    
    public void goToListeFicheDePoste(){
        List<FichePosteVM> viewModel = service.consulterLesFichesDePoste();
        Contenu contenu = new Contenu();
        JPanel panelListe = new JPanel(new GridLayout());
        JTable tableauFdP = new JTable(new FicheDePosteTableModel(viewModel));
        panelListe.add(new JScrollPane(tableauFdP), new GridLayout());
        contenu.setPanelIndex(panelListe);
        tableauFdP.setDefaultRenderer(Object.class, new BlueTableColoredCellRenderer());
        tableauFdP.getSelectionModel().addListSelectionListener((ListSelectionEvent e) ->{
            DetailsFichePosteVM detailVM = service.consulterLeDetailFicheDePoste(Integer.parseInt(tableauFdP.getValueAt(tableauFdP.getSelectedRow(), 0).toString()));
            contenu.setPanelDetail(new DetailsFicheDePoste(detailVM));
        });
        jLabelTitle.setText("Liste des fiches de poste");
        changerPanel(contenu);
    }
    
    public void goToCreerFicheDePoste(int dmdID){
        List<PresentationEntrepriseVM> presentations = service.consulterLesPresentationsEntreprise();
        CreerFicheDePoste jpanel = new CreerFicheDePoste(dmdID, service, presentations);
        jLabelTitle.setText("Création d'une fiche");
        changerPanel(jpanel);
    }
    
    
    public void goToListeCandidaturesDUneFiche(int identifiantFdP){
        List<CandidatureVM> viewModel = service.consulterLesCandidaturesPourUneFicheDePoste(identifiantFdP);
        Contenu contenu = new Contenu();
        JPanel panelListe = new JPanel(new GridLayout());
        JTable tableauCandidatures = new JTable(new CandidatureTableModel(viewModel));
        panelListe.add(new JScrollPane(tableauCandidatures), new GridLayout());
        contenu.setPanelIndex(panelListe);
        tableauCandidatures.setDefaultRenderer(Object.class, new BlueTableColoredCellRenderer());
        tableauCandidatures.getSelectionModel().addListSelectionListener((ListSelectionEvent e) ->{
            DetailsCandidatureVM detailVM = service.consulterLeDetailCandidature(Integer.parseInt(tableauCandidatures.getValueAt(tableauCandidatures.getSelectedRow(), 0).toString()));
            contenu.setPanelDetail(new DetailsCandidature(detailVM, service));
        });
        jLabelTitle.setText("Liste des candidatures de la fiche : " +identifiantFdP);
        changerPanel(contenu);
    }
    
    public void goToRecruterCandidat(int identifiantCandidature){
        RecruterCandidat jpanel = new RecruterCandidat(identifiantCandidature, service);
        jLabelTitle.setText("Recruter Un candidat");
        changerPanel(jpanel);
    }
    
    public void goToListeDemandesDeCompetence(){
        List<DmdCompetencesVM> viewModel = service.consulterLesDemandesDeCompetences();
        Contenu contenu = new Contenu();
        JPanel panelListe = new JPanel(new GridLayout());
        JTable tableauDmdCompetence = new JTable(new DmdCompetenceTableModel(viewModel));
        tableauDmdCompetence.setDefaultRenderer(Object.class, new BlueTableColoredCellRenderer());
        panelListe.add(new JScrollPane(tableauDmdCompetence), new GridLayout());
        contenu.setPanelIndex(panelListe);
        tableauDmdCompetence.getSelectionModel().addListSelectionListener((ListSelectionEvent e) -> {
            contenu.setPanelDetail(new DetailsDemandeDeCompetences(viewModel.stream().filter((data) -> data.getIdentifiant().toString().equals(tableauDmdCompetence.getValueAt(tableauDmdCompetence.getSelectedRow(), 0).toString())).findFirst().orElse(null)));
        });
        jLabelTitle.setText("Liste des demandes de compétences");
        changerPanel(contenu);
    }
    
    public static Canvas getCanvasInstance(){
        if(canvas == null){
            try {
                canvas = new Canvas();
            } catch (NamingException ex) {
                ErrorPopUp errorPopUp = new ErrorPopUp(ex.getMessage());
                Logger.getLogger(Canvas.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        return canvas;
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Canvas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Canvas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Canvas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Canvas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Canvas.getCanvasInstance().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JPanel boutons;
    private javax.swing.JButton jButtonCollaborateur;
    private javax.swing.JButton jButtonDemandeDeCompetence;
    private javax.swing.JButton jButtonFicheDePoste;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JPanel jPanelHeader;
    private javax.swing.JPanel jPanelTitreApplication;
    private javax.swing.JScrollPane jScrollPaneBody;
    private javax.swing.JSplitPane jSplitPane;
    private javax.swing.JPanel leftSplitBackground;
    private javax.swing.JPanel rightSplitBackground;
    // End of variables declaration//GEN-END:variables
}
