/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.supercompany.miragerh.ihm;

import javax.swing.JPanel;

/**
 * Définit une JPanel permettant de scinder les informations en deux parties
 * @author FlorianDELSOL
 */
public class Contenu extends javax.swing.JPanel {

    /**
     * Creates new form JPanelTable
     */
    public Contenu() {
        initComponents();
    }
    
    /**
     * Change le JPanel d'en haut
     * @param panel 
     */
    public void setPanelDetail(JPanel panel){
        jScrollPaneDetails.setViewportView(panel);
    }
    
    /**
     * Change le JPanel d'en bas
     * @param panel 
     */
    public void setPanelIndex(JPanel panel){
        jScrollPaneIndex.setViewportView(panel);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane = new javax.swing.JSplitPane();
        jScrollPaneDetails = new javax.swing.JScrollPane();
        jScrollPaneIndex = new javax.swing.JScrollPane();

        setBackground(new java.awt.Color(255, 255, 255));

        jSplitPane.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        jSplitPane.setTopComponent(jScrollPaneDetails);
        jSplitPane.setRightComponent(jScrollPaneIndex);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane, javax.swing.GroupLayout.DEFAULT_SIZE, 814, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane, javax.swing.GroupLayout.DEFAULT_SIZE, 374, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPaneDetails;
    private javax.swing.JScrollPane jScrollPaneIndex;
    private javax.swing.JSplitPane jSplitPane;
    // End of variables declaration//GEN-END:variables
}
