/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.supercompany.miragerh.ihm.details;

import com.supercompany.miragerh.ihm.Canvas;
import com.supercompany.miragerh.ihm.popup.ConfirmationPopUp;
import fr.jaschavolp.m1.jee.mirageshared.candidature.DetailsCandidatureVM;
import fr.jaschavolp.m1.jee.mirageshared.shared.services.ServicesRHRemote;

/**
 * Défini une JPanel personnalisé visualisant l'ensemble des informations d'une candidature
 * @author FlorianDELSOL
 */
public class DetailsCandidature extends javax.swing.JPanel {
    
    private DetailsCandidatureVM data;
    
    private ServicesRHRemote service;

    /**
     * Créer une nouvelle instance de classe DetailsCandidature
     * @param data données sur une candidature
     * @param service service permettant de communiquer avec le serveur
     */
    public DetailsCandidature(DetailsCandidatureVM data, ServicesRHRemote service) {
        initComponents();
        this.data = data;
        this.actualize();
    }
    
    private void actualize(){
        if(data != null){
            jLabelCandIdentifiantData.setText(data.getIdentifiant().toString());
            jLabelLettreDeMotivationData.setText(data.getLettreMotivation());
            jLabelCandIdentifiantData.setText(data.getDetailsCandidat().getIdentifiant().toString());
            jLabelCandIdentiteeData.setText(data.getDetailsCandidat().getPrenom() + data.getDetailsCandidat().getNom().toUpperCase() );
            jLabelCandEmailData.setText(data.getDetailsCandidat().getEmail());
            jLabelCandTelephoneData.setText(data.getDetailsCandidat().getNumero());
            jLabelFdPIdentifiantData.setText(data.getDetailsFichePoste().getIdentifiant().toString());
            jLabelFdPNomData.setText(data.getDetailsFichePoste().getNom());
            jLabelFdPPresentationData.setText(data.getDetailsFichePoste().getPresentationPoste());
            jLabelFdPPresentationEntrepriseData.setText(data.getDetailsFichePoste().getPresentationEntreprise());
            
            jButtonFeuVertRH.setEnabled(data.getChoixRH() == null);
            jButtonRecruter.setEnabled(data.getChoixCODIR() != null && data.getChoixCODIR() && data.getChoixRH() != null && data.getChoixRH() && data.getChoixCandidat() != null && data.getChoixCandidat());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel17 = new javax.swing.JPanel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jPanelIdentifiant = new javax.swing.JPanel();
        jLabelIdentifiantTitle = new javax.swing.JLabel();
        jLabelIdentifiantData = new javax.swing.JLabel();
        jPanelLettreDeMotivation = new javax.swing.JPanel();
        jLabelLettreDeMotivationTitle = new javax.swing.JLabel();
        jLabelLettreDeMotivationData = new javax.swing.JLabel();
        jPanelCandidat = new javax.swing.JPanel();
        jLabelCandidatTitle = new javax.swing.JLabel();
        jPanelCandIdentifiant = new javax.swing.JPanel();
        jLabelCandIdentifiantTitle = new javax.swing.JLabel();
        jLabelCandIdentifiantData = new javax.swing.JLabel();
        jPanelCandIdentitee = new javax.swing.JPanel();
        jLabelCandIdentiteeTitle = new javax.swing.JLabel();
        jLabelCandIdentiteeData = new javax.swing.JLabel();
        jPanelCandEmail = new javax.swing.JPanel();
        jLabelCandEmailTitle = new javax.swing.JLabel();
        jLabelCandEmailData = new javax.swing.JLabel();
        jPanelCandTelephone = new javax.swing.JPanel();
        jLabelCandTelephoneTitle = new javax.swing.JLabel();
        jLabelCandTelephoneData = new javax.swing.JLabel();
        jPanelFicheDePoste = new javax.swing.JPanel();
        jLabelFicheDePoste = new javax.swing.JLabel();
        jPanelFdPIdentifiant = new javax.swing.JPanel();
        jLabelFdPIdentifiantTitle = new javax.swing.JLabel();
        jLabelFdPIdentifiantData = new javax.swing.JLabel();
        jPanelFdPNom = new javax.swing.JPanel();
        jLabelFdPNomTitle = new javax.swing.JLabel();
        jLabelFdPNomData = new javax.swing.JLabel();
        jPanelFdPPresentation = new javax.swing.JPanel();
        jLabelFdPPresentationTitle = new javax.swing.JLabel();
        jLabelFdPPresentationData = new javax.swing.JLabel();
        jPanelFdPPresentationEntreprise = new javax.swing.JPanel();
        jLabelFdPPresentationEntrepriseTitle = new javax.swing.JLabel();
        jLabelFdPPresentationEntrepriseData = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButtonFeuVertRH = new javax.swing.JButton();
        jButtonRecruter = new javax.swing.JButton();

        jLabel37.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel37.setText("Présentation de l'entreprise");

        jLabel38.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel38.setText("Id :");

        jLabel39.setText("identifiant");

        jLabel40.setText("Ici, la présentation du poste.");
        jLabel40.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel40, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel17Layout.createSequentialGroup()
                        .addComponent(jLabel37)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel38)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel39)
                        .addGap(0, 593, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel37)
                    .addComponent(jLabel38)
                    .addComponent(jLabel39))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel40, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        setBackground(new java.awt.Color(255, 255, 255));

        jPanelIdentifiant.setBackground(new java.awt.Color(250, 250, 255));

        jLabelIdentifiantTitle.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabelIdentifiantTitle.setText("Identifiant :");

        jLabelIdentifiantData.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabelIdentifiantData.setText("identifiant");

        javax.swing.GroupLayout jPanelIdentifiantLayout = new javax.swing.GroupLayout(jPanelIdentifiant);
        jPanelIdentifiant.setLayout(jPanelIdentifiantLayout);
        jPanelIdentifiantLayout.setHorizontalGroup(
            jPanelIdentifiantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelIdentifiantLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelIdentifiantTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelIdentifiantData)
                .addContainerGap(690, Short.MAX_VALUE))
        );
        jPanelIdentifiantLayout.setVerticalGroup(
            jPanelIdentifiantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelIdentifiantLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelIdentifiantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelIdentifiantTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelIdentifiantData))
                .addContainerGap())
        );

        jPanelLettreDeMotivation.setBackground(new java.awt.Color(250, 250, 255));

        jLabelLettreDeMotivationTitle.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabelLettreDeMotivationTitle.setText("Lettre de motivation");

        jLabelLettreDeMotivationData.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabelLettreDeMotivationData.setText("Ici, la lettre de motivation.");
        jLabelLettreDeMotivationData.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout jPanelLettreDeMotivationLayout = new javax.swing.GroupLayout(jPanelLettreDeMotivation);
        jPanelLettreDeMotivation.setLayout(jPanelLettreDeMotivationLayout);
        jPanelLettreDeMotivationLayout.setHorizontalGroup(
            jPanelLettreDeMotivationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLettreDeMotivationLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelLettreDeMotivationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelLettreDeMotivationData, javax.swing.GroupLayout.DEFAULT_SIZE, 912, Short.MAX_VALUE)
                    .addGroup(jPanelLettreDeMotivationLayout.createSequentialGroup()
                        .addComponent(jLabelLettreDeMotivationTitle)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelLettreDeMotivationLayout.setVerticalGroup(
            jPanelLettreDeMotivationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLettreDeMotivationLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelLettreDeMotivationTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelLettreDeMotivationData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanelCandidat.setBackground(new java.awt.Color(250, 250, 255));

        jLabelCandidatTitle.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabelCandidatTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCandidatTitle.setText("Candidat");
        jLabelCandidatTitle.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jPanelCandIdentifiant.setBackground(new java.awt.Color(250, 250, 255));

        jLabelCandIdentifiantTitle.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabelCandIdentifiantTitle.setText("Identifiant :");

        jLabelCandIdentifiantData.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabelCandIdentifiantData.setText("identifiant");

        javax.swing.GroupLayout jPanelCandIdentifiantLayout = new javax.swing.GroupLayout(jPanelCandIdentifiant);
        jPanelCandIdentifiant.setLayout(jPanelCandIdentifiantLayout);
        jPanelCandIdentifiantLayout.setHorizontalGroup(
            jPanelCandIdentifiantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCandIdentifiantLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelCandIdentifiantTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelCandIdentifiantData)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelCandIdentifiantLayout.setVerticalGroup(
            jPanelCandIdentifiantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCandIdentifiantLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCandIdentifiantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCandIdentifiantTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelCandIdentifiantData))
                .addContainerGap())
        );

        jPanelCandIdentitee.setBackground(new java.awt.Color(250, 250, 255));

        jLabelCandIdentiteeTitle.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabelCandIdentiteeTitle.setText("Identité :");

        jLabelCandIdentiteeData.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabelCandIdentiteeData.setText("Prénom NOM");

        javax.swing.GroupLayout jPanelCandIdentiteeLayout = new javax.swing.GroupLayout(jPanelCandIdentitee);
        jPanelCandIdentitee.setLayout(jPanelCandIdentiteeLayout);
        jPanelCandIdentiteeLayout.setHorizontalGroup(
            jPanelCandIdentiteeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCandIdentiteeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelCandIdentiteeTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelCandIdentiteeData)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelCandIdentiteeLayout.setVerticalGroup(
            jPanelCandIdentiteeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCandIdentiteeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCandIdentiteeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCandIdentiteeTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelCandIdentiteeData))
                .addContainerGap())
        );

        jPanelCandEmail.setBackground(new java.awt.Color(250, 250, 255));

        jLabelCandEmailTitle.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabelCandEmailTitle.setText("E-mail :");

        jLabelCandEmailData.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabelCandEmailData.setText("prenom.nom@gmail.fr");

        javax.swing.GroupLayout jPanelCandEmailLayout = new javax.swing.GroupLayout(jPanelCandEmail);
        jPanelCandEmail.setLayout(jPanelCandEmailLayout);
        jPanelCandEmailLayout.setHorizontalGroup(
            jPanelCandEmailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCandEmailLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelCandEmailTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelCandEmailData)
                .addContainerGap(637, Short.MAX_VALUE))
        );
        jPanelCandEmailLayout.setVerticalGroup(
            jPanelCandEmailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCandEmailLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCandEmailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCandEmailTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelCandEmailData))
                .addContainerGap())
        );

        jPanelCandTelephone.setBackground(new java.awt.Color(250, 250, 255));

        jLabelCandTelephoneTitle.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabelCandTelephoneTitle.setText("Téléphone :");

        jLabelCandTelephoneData.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabelCandTelephoneData.setText("06 67 45 89 23");

        javax.swing.GroupLayout jPanelCandTelephoneLayout = new javax.swing.GroupLayout(jPanelCandTelephone);
        jPanelCandTelephone.setLayout(jPanelCandTelephoneLayout);
        jPanelCandTelephoneLayout.setHorizontalGroup(
            jPanelCandTelephoneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCandTelephoneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelCandTelephoneTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelCandTelephoneData)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelCandTelephoneLayout.setVerticalGroup(
            jPanelCandTelephoneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCandTelephoneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCandTelephoneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCandTelephoneTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelCandTelephoneData))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanelCandidatLayout = new javax.swing.GroupLayout(jPanelCandidat);
        jPanelCandidat.setLayout(jPanelCandidatLayout);
        jPanelCandidatLayout.setHorizontalGroup(
            jPanelCandidatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelCandidatTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelCandIdentifiant, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelCandIdentitee, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelCandEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelCandTelephone, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelCandidatLayout.setVerticalGroup(
            jPanelCandidatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCandidatLayout.createSequentialGroup()
                .addComponent(jLabelCandidatTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelCandIdentifiant, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelCandIdentitee, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelCandEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelCandTelephone, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelFicheDePoste.setBackground(new java.awt.Color(250, 250, 255));

        jLabelFicheDePoste.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabelFicheDePoste.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelFicheDePoste.setText("Fiche de poste");

        jPanelFdPIdentifiant.setBackground(new java.awt.Color(250, 250, 255));

        jLabelFdPIdentifiantTitle.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabelFdPIdentifiantTitle.setText("Identifiant :");

        jLabelFdPIdentifiantData.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabelFdPIdentifiantData.setText("identifiant");

        javax.swing.GroupLayout jPanelFdPIdentifiantLayout = new javax.swing.GroupLayout(jPanelFdPIdentifiant);
        jPanelFdPIdentifiant.setLayout(jPanelFdPIdentifiantLayout);
        jPanelFdPIdentifiantLayout.setHorizontalGroup(
            jPanelFdPIdentifiantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFdPIdentifiantLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelFdPIdentifiantTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelFdPIdentifiantData)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelFdPIdentifiantLayout.setVerticalGroup(
            jPanelFdPIdentifiantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFdPIdentifiantLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelFdPIdentifiantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelFdPIdentifiantLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabelFdPIdentifiantData))
                    .addComponent(jLabelFdPIdentifiantTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanelFdPNom.setBackground(new java.awt.Color(250, 250, 255));

        jLabelFdPNomTitle.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabelFdPNomTitle.setText("Nom de la fiche");

        jLabelFdPNomData.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabelFdPNomData.setText("Nom de la fiche");
        jLabelFdPNomData.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout jPanelFdPNomLayout = new javax.swing.GroupLayout(jPanelFdPNom);
        jPanelFdPNom.setLayout(jPanelFdPNomLayout);
        jPanelFdPNomLayout.setHorizontalGroup(
            jPanelFdPNomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFdPNomLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelFdPNomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelFdPNomLayout.createSequentialGroup()
                        .addComponent(jLabelFdPNomTitle)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLabelFdPNomData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelFdPNomLayout.setVerticalGroup(
            jPanelFdPNomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFdPNomLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelFdPNomTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelFdPNomData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanelFdPPresentation.setBackground(new java.awt.Color(250, 250, 255));

        jLabelFdPPresentationTitle.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabelFdPPresentationTitle.setText("Présentation du poste");

        jLabelFdPPresentationData.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabelFdPPresentationData.setText("Ici, la présentation du poste");
        jLabelFdPPresentationData.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout jPanelFdPPresentationLayout = new javax.swing.GroupLayout(jPanelFdPPresentation);
        jPanelFdPPresentation.setLayout(jPanelFdPPresentationLayout);
        jPanelFdPPresentationLayout.setHorizontalGroup(
            jPanelFdPPresentationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFdPPresentationLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelFdPPresentationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelFdPPresentationLayout.createSequentialGroup()
                        .addComponent(jLabelFdPPresentationTitle)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLabelFdPPresentationData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelFdPPresentationLayout.setVerticalGroup(
            jPanelFdPPresentationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFdPPresentationLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelFdPPresentationTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelFdPPresentationData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanelFdPPresentationEntreprise.setBackground(new java.awt.Color(250, 250, 255));

        jLabelFdPPresentationEntrepriseTitle.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabelFdPPresentationEntrepriseTitle.setText("Présentation de l'entreprise");

        jLabelFdPPresentationEntrepriseData.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabelFdPPresentationEntrepriseData.setText("Ici, la présentation de l'entreprise");
        jLabelFdPPresentationEntrepriseData.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout jPanelFdPPresentationEntrepriseLayout = new javax.swing.GroupLayout(jPanelFdPPresentationEntreprise);
        jPanelFdPPresentationEntreprise.setLayout(jPanelFdPPresentationEntrepriseLayout);
        jPanelFdPPresentationEntrepriseLayout.setHorizontalGroup(
            jPanelFdPPresentationEntrepriseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFdPPresentationEntrepriseLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelFdPPresentationEntrepriseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelFdPPresentationEntrepriseData, javax.swing.GroupLayout.DEFAULT_SIZE, 912, Short.MAX_VALUE)
                    .addGroup(jPanelFdPPresentationEntrepriseLayout.createSequentialGroup()
                        .addComponent(jLabelFdPPresentationEntrepriseTitle)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelFdPPresentationEntrepriseLayout.setVerticalGroup(
            jPanelFdPPresentationEntrepriseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFdPPresentationEntrepriseLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelFdPPresentationEntrepriseTitle)
                .addGap(10, 10, 10)
                .addComponent(jLabelFdPPresentationEntrepriseData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanelFicheDePosteLayout = new javax.swing.GroupLayout(jPanelFicheDePoste);
        jPanelFicheDePoste.setLayout(jPanelFicheDePosteLayout);
        jPanelFicheDePosteLayout.setHorizontalGroup(
            jPanelFicheDePosteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelFicheDePoste, javax.swing.GroupLayout.DEFAULT_SIZE, 936, Short.MAX_VALUE)
            .addComponent(jPanelFdPIdentifiant, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelFdPNom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelFdPPresentation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelFdPPresentationEntreprise, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelFicheDePosteLayout.setVerticalGroup(
            jPanelFicheDePosteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFicheDePosteLayout.createSequentialGroup()
                .addComponent(jLabelFicheDePoste, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelFdPIdentifiant, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelFdPNom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelFdPPresentation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelFdPPresentationEntreprise, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(50, 50, 98));

        jButtonFeuVertRH.setBackground(new java.awt.Color(50, 50, 98));
        jButtonFeuVertRH.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButtonFeuVertRH.setForeground(new java.awt.Color(255, 255, 255));
        jButtonFeuVertRH.setText("Mettre son feu vert (RH)");
        jButtonFeuVertRH.setFocusable(false);
        jButtonFeuVertRH.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonFeuVertRH.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonFeuVertRH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFeuVertRHActionPerformed(evt);
            }
        });

        jButtonRecruter.setBackground(new java.awt.Color(50, 50, 98));
        jButtonRecruter.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButtonRecruter.setForeground(new java.awt.Color(255, 255, 255));
        jButtonRecruter.setText("Recruter");
        jButtonRecruter.setFocusable(false);
        jButtonRecruter.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonRecruter.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonRecruter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRecruterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jButtonFeuVertRH)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonRecruter)
                .addGap(0, 657, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButtonFeuVertRH)
            .addComponent(jButtonRecruter)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelIdentifiant, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelCandidat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelFicheDePoste, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelLettreDeMotivation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jPanelIdentifiant, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelLettreDeMotivation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelCandidat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelFicheDePoste, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 791, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonFeuVertRHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFeuVertRHActionPerformed
        service.donnerLeFeuxVertRH(data.getIdentifiant());
        ConfirmationPopUp popup = new ConfirmationPopUp("Le feu vert RH à bien été pris en compte ! merci");
    }//GEN-LAST:event_jButtonFeuVertRHActionPerformed

    private void jButtonRecruterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRecruterActionPerformed
        Canvas.getCanvasInstance().goToRecruterCandidat(data.getIdentifiant());
    }//GEN-LAST:event_jButtonRecruterActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonFeuVertRH;
    private javax.swing.JButton jButtonRecruter;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabelCandEmailData;
    private javax.swing.JLabel jLabelCandEmailTitle;
    private javax.swing.JLabel jLabelCandIdentifiantData;
    private javax.swing.JLabel jLabelCandIdentifiantTitle;
    private javax.swing.JLabel jLabelCandIdentiteeData;
    private javax.swing.JLabel jLabelCandIdentiteeTitle;
    private javax.swing.JLabel jLabelCandTelephoneData;
    private javax.swing.JLabel jLabelCandTelephoneTitle;
    private javax.swing.JLabel jLabelCandidatTitle;
    private javax.swing.JLabel jLabelFdPIdentifiantData;
    private javax.swing.JLabel jLabelFdPIdentifiantTitle;
    private javax.swing.JLabel jLabelFdPNomData;
    private javax.swing.JLabel jLabelFdPNomTitle;
    private javax.swing.JLabel jLabelFdPPresentationData;
    private javax.swing.JLabel jLabelFdPPresentationEntrepriseData;
    private javax.swing.JLabel jLabelFdPPresentationEntrepriseTitle;
    private javax.swing.JLabel jLabelFdPPresentationTitle;
    private javax.swing.JLabel jLabelFicheDePoste;
    private javax.swing.JLabel jLabelIdentifiantData;
    private javax.swing.JLabel jLabelIdentifiantTitle;
    private javax.swing.JLabel jLabelLettreDeMotivationData;
    private javax.swing.JLabel jLabelLettreDeMotivationTitle;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelCandEmail;
    private javax.swing.JPanel jPanelCandIdentifiant;
    private javax.swing.JPanel jPanelCandIdentitee;
    private javax.swing.JPanel jPanelCandTelephone;
    private javax.swing.JPanel jPanelCandidat;
    private javax.swing.JPanel jPanelFdPIdentifiant;
    private javax.swing.JPanel jPanelFdPNom;
    private javax.swing.JPanel jPanelFdPPresentation;
    private javax.swing.JPanel jPanelFdPPresentationEntreprise;
    private javax.swing.JPanel jPanelFicheDePoste;
    private javax.swing.JPanel jPanelIdentifiant;
    private javax.swing.JPanel jPanelLettreDeMotivation;
    // End of variables declaration//GEN-END:variables
}
